CREATE TABLE attendance_adjustment_requests (
  id BIGINT NOT NULL AUTO_INCREMENT,
  session_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  requested_by_id BIGINT NOT NULL,
  original_check_in DATETIME(6) NOT NULL,
  original_check_out DATETIME(6) NULL,
  requested_check_in DATETIME(6) NOT NULL,
  requested_check_out DATETIME(6) NOT NULL,
  reason VARCHAR(500) NOT NULL,
  status VARCHAR(24) NOT NULL,
  manager_approved_by_id BIGINT NULL,
  manager_approved_at DATETIME(6) NULL,
  admin_approved_by_id BIGINT NULL,
  admin_approved_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  version BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY idx_attendance_adjustment_user_created (user_id, created_at),
  KEY idx_attendance_adjustment_status_created (status, created_at),
  CONSTRAINT fk_attendance_adjustment_session FOREIGN KEY (session_id) REFERENCES attendance_sessions(id),
  CONSTRAINT fk_attendance_adjustment_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_attendance_adjustment_requester FOREIGN KEY (requested_by_id) REFERENCES users(id),
  CONSTRAINT fk_attendance_adjustment_manager FOREIGN KEY (manager_approved_by_id) REFERENCES users(id),
  CONSTRAINT fk_attendance_adjustment_admin FOREIGN KEY (admin_approved_by_id) REFERENCES users(id),
  CONSTRAINT chk_attendance_adjustment_times CHECK (requested_check_out >= requested_check_in),
  CONSTRAINT chk_attendance_adjustment_status CHECK (status IN ('PENDING_MANAGER', 'PENDING_ADMIN', 'APPROVED', 'REJECTED_MANAGER', 'REJECTED_ADMIN'))
) ENGINE=InnoDB;